const messages = {
  en: {
    common: {
      header: {
        brand: 'Escáner Legislativo MX',
      },
      menu: {
        scanner: 'Scanner',
        about: 'About',
      },
      footer: {
        developedBy: 'Developed by',
        supportedBy: 'Supported by',
        copy: 'Escáner Legislativo MX — Some rights reserved (AGPL-3.0 code; NormTrace content CC BY 4.0).',
        disclaimer:
          'Results are generated by curated-vocabulary matching. They indicate thematic presence, not content assessment.',
        tech: 'Built with open-source technology (tipi / escáner2030 stack) and the NormTrace protocol.',
      },
      cookies: {
        info: 'This site uses cookies to ensure you get the best experience.',
        accept: 'Accept',
        decline: 'Decline',
      },
    },
    about: {
      title: 'About',
      content: `<p><strong>Escáner Legislativo MX</strong> is a tool that automatically identifies and tags Mexican legislative texts —bills from the Chamber of Deputies, laws in force, committee reports— against the 2030 Agenda and its 17 Sustainable Development Goals, and traces the legal structure they create.</p>
    <h4>How does it work?</h4>
    <p>The scanner works in two complementary layers:</p>
    <p><strong>1. Thematic tagging.</strong> A knowledge base of Mexican institutional vocabulary (agencies, programmes, general laws, official standards) classifies the text by its relation to the SDGs and their targets through curated term matching. It indicates <em>thematic presence</em>, not content assessment.</p>
    <p><strong>2. Structural analysis (NormTrace protocol).</strong> Over the legal units of the text (article, fraction, subsection), an assisted coding identifies which actor is bound or empowered, through which procedure, coordination across levels of government, sanction or safeguard, and what kind of gap it presents. It is a preliminary reading that always keeps its source citation and review status.</p>
    <h4>Can it be adapted to other contexts?</h4>
    <p>Yes. The tool is built with free and open-source software, which allows it to be adapted to other regulatory frameworks or contexts (academic, public administration, civil society organisations) quickly and responsively.</p>
    <h4>Important note</h4>
    <p>Tagging results are generated by curated-vocabulary matching: they indicate thematic presence, not content assessment. The structural coding is preliminary, assisted by a language model under the NormTrace protocol; <strong>it is not a legal opinion or a compliance assessment</strong> and requires specialist review. Every record keeps its source citation for verification.</p>`,
    },
    page404: {
      title: 'Page not found',
      body: 'The page you are looking for does not exist.',
      button: 'Go to the home page',
    },
    scanned: {},
    scanner: {
      title: 'Scan any text',
      subtitle:
        'Label and visualise the content of your text in relation to the 2030 Global Goals',
      info: `<p>
      <strong>How does it work?</strong>
      Copy and paste the contents of the text to be analysed in the box shown below or select a file from your computer. Once you have it simply hit the Scan button and enjoy the automatic visualisations generated by the tool.
      </p>
      <p>
      <strong>Scaner 2030</strong>
      is an open access and free use tool that allows you to detect and obtain visualisations of the presence of the different Sustainable Development Goals (SDGs) in any text.
      </p>`,
      form: {
        placeholder: 'Insert the text you want to scan...',
        file: 'Upload a file',
        weight: 'The max file size allowed is 20 MB.',
        button: 'Scan now',
        buttonProgress: 'In progress...',
        start: 'Start process',
      },
      result: {
        scanning: 'Scanning document...',
        subtitle_estimated:
          "It will take approximately {estimatedTime} seconds to show you the results. Please don't leave…",
        subtitle: "Please be patient. We're working on it.",
        notFound:
          "Scanner 2030 didn't found any matches between your text and the 2030 Agenda",
      },
      save: {
        title: 'Save the results',
        body: 'You can re-access the results of your scanned text without downloading the file. When saving the result, a link will be generated that you can keep and visit whenever you need it.',
        button: 'Save',
      },
      deep: {
        toggle: 'Structural analysis (NormTrace) by legal unit',
        hint: 'Codes each legal unit (article, fraction) after the quick scan.',
      },
      structural: {
        title: 'Structural analysis by legal unit',
        loading: 'Coding the legal units…',
        empty: 'No coded units to show.',
        summary: 'Units analysed: {analyzed} · not analysed (budget): {skipped}',
        export: 'Print / Export PDF',
        disclaimer:
          'Preliminary coding assisted by a language model under the NormTrace protocol. It is not a legal opinion or a compliance assessment; it requires specialist review. Each record keeps its source citation for verification.',
        col: {
          unit: 'Unit',
          actor: 'Actor',
          duty: 'Duty / Power',
          procedure: 'Procedure',
          coordination: 'Coordination',
          gap: 'Gap type',
          confidence: 'Confidence',
        },
      },
    },
    components: {
      scannerSunburst: {
        title: 'Results distribution',
      },
      scannerTable: {
        sdg: 'SDG',
        goal: 'Goal',
        tag: 'Tag',
        findings: 'Findings',
      },
      scannerVisualizations: {
        title: 'Distribution of the results',
        zoom: 'You can zoom clicking in each of the portions.',
        maxShown: 'We show a maximum of {num} terms.',
        compare: {
          title: 'Compare the results:',
          info: 'Select a reference text, among those we have loaded in our system, to be able to compare with the results of your tagged text.',
          label: 'Compare with...',
          placeholder: 'Select one',
          empty: 'Empty list',
        },
        detailed: {
          title: 'Detailed results:',
          infoLength:
            'We show you only 10 of {num} results, download the file to see the rest.',
          info: 'You can also get the data downloading the file.',
          button: 'Download the results',
          downloadInfo: 'The results will be downloaded in CSV format.',
        },
      },
      scannerWordscloud: {
        title: 'Terms most found',
      },
    },
  },
  es: {
    common: {
      header: {
        brand: 'Escáner Legislativo MX',
      },
      menu: {
        scanner: 'Escáner',
        about: 'Acerca',
      },
      footer: {
        developedBy: 'Desarrollado por',
        supportedBy: 'Con el apoyo de',
        copy: 'Escáner Legislativo MX — Algunos derechos reservados (código AGPL-3.0; contenido NormTrace CC BY 4.0).',
        disclaimer:
          'Resultados generados por coincidencia de vocabulario curado. Indican presencia temática, no evaluación de contenido.',
        tech: 'Construido con tecnología de código abierto (stack tipi / escáner2030) y el protocolo NormTrace.',
      },
      cookies: {
        info: 'Este sitio usa cookies para asegurarte la mejor experiencia web.',
        accept: 'Aceptar',
        decline: 'Rechazar',
      },
    },
    about: {
      title: 'Acerca',
      content: `<p>
      <b>Escáner Legislativo MX</b> es una herramienta que identifica y
      etiqueta de manera automática textos legislativos mexicanos
      —iniciativas de la Cámara de Diputados, leyes vigentes, dictámenes—
      en clave de Agenda 2030 y sus 17 Objetivos de Desarrollo Sostenible,
      y traza la estructura jurídica que crean.
    </p>
    <h4>¿Cómo funciona?</h4>
    <p>
      El escáner trabaja en dos capas complementarias:
    </p>
    <p>
      <b>1. Etiquetado temático.</b> Una base de conocimiento con
      vocabulario institucional mexicano (dependencias, programas, leyes
      generales, normas oficiales) permite, mediante coincidencia de
      términos curados, clasificar el texto según su relación con los ODS y
      sus metas. Indica <i>presencia temática</i>, no evaluación de
      contenido.
    </p>
    <p>
      <b>2. Análisis estructural (protocolo NormTrace).</b> Sobre las
      unidades jurídicas del texto (artículo, fracción, inciso), una
      codificación asistida identifica qué actor queda obligado o
      facultado, con qué procedimiento, coordinación entre órdenes de
      gobierno, sanción o salvaguarda, y qué tipo de brecha presenta. Es
      una lectura preliminar que conserva siempre su cita fuente y su
      estatus de revisión.
    </p>
    <h4>¿Puede adaptarse a otros contextos?</h4>
    <p>
      Sí. La herramienta está construida con software libre y de código
      abierto, lo que permite adaptarla a otros marcos normativos o
      contextos (académicos, administración pública, organizaciones de la
      sociedad civil) de manera rápida y ajustada a cada necesidad.
    </p>
    <h4>Nota importante</h4>
    <p>
      Los resultados del etiquetado se generan por coincidencia de
      vocabulario curado: indican presencia temática, no evaluación de
      contenido. La codificación estructural es preliminar, asistida por
      modelo de lenguaje bajo el protocolo NormTrace; <b>no constituye
      dictamen jurídico ni evaluación de cumplimiento</b> y requiere
      revisión de especialista. Cada registro conserva su cita fuente para
      verificación.
    </p>`,
    },
    page404: {
      title: '¿Te has perdido?',
      body: 'Regresa a la página de inicio para encontrar lo que realmente estás buscando.',
      button: 'Volver al inicio',
    },
    scanner: {
      title: 'Escanea un texto',
      subtitle:
        'Etiqueta y visualiza el contenido de tu texto en relación con los objetivos de la Agenda 2030',
      info: `<p>
      <strong>¿Cómo funciona?</strong>
      Copia y pega el contenido del texto a analizar en la caja que se muestra a continuación o selecciona un archivo de tu ordenador. Una vez que lo tengas simplemente dale al botón de Escanear y disfruta de las visualizaciones automáticas que genera la herramienta.
      </p>
      <p>
      <strong>Escáner Legislativo MX</strong>
      es una herramienta de uso gratuito y libre que te permite detectar y obtener visualizaciones de la presencia de los diferentes Objetivos de Desarrollo Sostenible (ODS) en cualquier texto legislativo mexicano.
      </p>`,
      form: {
        placeholder: 'Inserta aquí el texto que quieras escanear...',
        file: 'Sube un archivo',
        weight: 'El peso máximo soportado de los archivos es de 20 MB.',
        button: 'Escanear',
        buttonProgress: 'En proceso...',
        start: 'Iniciar proceso',
      },
      result: {
        scanning: 'Escaneando documento',
        subtitle_estimated:
          'Tardaremos aproximadamente {estimatedTime} segundos en presentarte los resultados. No te vayas...',
        subtitle: 'Ten paciencia. Estamos trabajando en ello.',
        notFound:
          'No hemos encontrado ninguna coincidencia entre tu texto y nuestras etiquetas.',
      },
      save: {
        title: 'Guarda el resultado',
        body: 'Puedes volver a acceder a los resultados de tu texto escaneado sin necesidad de descargarte el archivo. Al guardar el resutado, se generará un enlace que pudes conservar y visitar siempre que lo necesites.',
        button: 'Guardar',
      },
      deep: {
        toggle: 'Análisis estructural (NormTrace) por unidad jurídica',
        hint: 'Codifica cada unidad jurídica (artículo, fracción) después del escaneo rápido.',
      },
      structural: {
        title: 'Análisis estructural por unidad jurídica',
        loading: 'Codificando las unidades jurídicas…',
        empty: 'No hay unidades codificadas para mostrar.',
        summary: 'Unidades analizadas: {analyzed} · sin analizar (presupuesto): {skipped}',
        export: 'Imprimir / Exportar PDF',
        disclaimer:
          'Codificación preliminar asistida por modelo de lenguaje bajo el protocolo NormTrace. No constituye dictamen jurídico ni evaluación de cumplimiento; requiere revisión de especialista. Cada registro conserva su cita fuente para verificación.',
        col: {
          unit: 'Unidad',
          actor: 'Actor',
          duty: 'Deber / Facultad',
          procedure: 'Procedimiento',
          coordination: 'Coordinación',
          gap: 'Tipo de brecha',
          confidence: 'Confianza',
        },
      },
    },
    components: {
      scannerSunburst: {
        title: 'Distribución de resultados',
      },
      scannerTable: {
        sdg: 'ODS',
        goal: 'Meta',
        tag: 'Etiqueta',
        findings: 'Apariciones',
      },
      scannerVisualizations: {
        title: 'Distribución de los resultados',
        zoom: 'Puedes hacer zoom haciendo clic en cada una de las porciones.',
        maxShown: 'Se muestran un máximo de {num} términos.',
        compare: {
          title: 'Compara los resultados:',
          info: 'Selecciona un texto de referencia, entre los que tenemos cargados en nuestro sistema, para poder comparar con los resultados de tu texto etiquetado.',
          label: 'Comparar con...',
          placeholder: 'Selecciona uno',
          empty: 'Listado vacío',
        },
        detailed: {
          title: 'Resultados detallados:',
          infoLength:
            'Aquí solo te mostramos 10 resultados de {num}, para ver el resto descarga el archivo.',
          info: 'También puedes obtener los datos descargando el archivo.',
          button: 'Descarga tus resultados',
          downloadInfo: 'Los resultados se descargarán en formato CSV.',
        },
      },
      scannerWordscloud: {
        title: 'Términos con más apariciones',
      },
    },
  },
};

export default messages;
